### ISSUE TITLE
Issue with macOS and OpenGL library location in python Env

### ISSUE THREAD

**Issue by mfbenitezp** [dabreegster/uatk-aspics#14]
Apparently, BigSur is not longer support OpenGL library or other system libraries in the standard locations
in the file system and instead uses a cache. When I run 
`poetry run python gui.py -p model_parameters/default.yml`
I got 
`ImportError: ('Unable to load OpenGL library', "dlopen(OpenGL, 0x000A):`

Earlier we found the way to address that uisng the suggestion from: [https://github.com/PixarAnimationStudios/USD/issues/1372](https://github.com/PixarAnimationStudios/USD/issues/1372)

The way to address that was:

- Find the file in **OpenGL/platform/ctypesloader.py,**  in the python Env created by Poetry.

- Update/Edit the line

`  fullName = util.find\_library( name ) `

to

` fullName = '/System/Library/Frameworks/OpenGL.framework/OpenGL'
`

**Comment by dabreegster** [comment]
From reading the issue, it was fixed properly in upstream Python in November 2020. People then made some backports from Python 3.8 and 3.9 maybe. I think if we can figure out which version of Python has the fix, we can enable that in `pyproject.toml` (`python = "^3.8"`) and avoid this entirely. I'll see if I can first reproduce the problem on my macbook.

**Comment by mfbenitezp** [comment]
Although, I though we have already been using python >3.8. Non important at this very moment.
